language: node_js
node_js:
  - 8
deploy:
  provider: heroku
  api_key:
    secure: grcxCEX3bYTAuAcSMvaQHKkgNwFkn10DqPhWLOPw6uD99FUFELEDVRBpiyfyNT7/XnCaw2R9hRW/9rlEmnlptERfQoLIICNVrqKws0NBtYYJ8pY8a5LjziMBUUtiC7RuBzKffjUb9VGQlKMViwRWxt+MJ3bw5fD9TNZdmie2P9cE4xx9Y8ywGDKTV697gaFvAcIQqGSuTFcTlxaKQF/9z5V4W+8mRXE14/H/i9SmtaPc+4TQSSdDonZ3H+IgsooW0oxh4MmSLF+YJQYLGy7pVzJkVGEuV5XNLAjZBETUaVrXhuAt9/vTezCTUpMV1dZvQ+7BCGYJ/hWGH83H1J6yXNqabe7Qq8Hg6l0esYWpBa6ZEdWqOEl0M9jxa+HBJCkb+mC1XfnEKrtZEW47yNtOT2ACuJ8E+WHPnt8ADnI6OrkBzbbICn8JXh9yQgw9gJTT0pC7Y2+ON1uclgyexlFEzRjJCUnwr6/4e57/DxFfaaU8j6tyRVwmHHpQxDKANEf4hvf9LjaSs2dqrz1Qx//4K9O45HLcCeM3plQTHV5c0eTnuzA4NiWYRmKngVMF9kPNZzKENsds4br3Zf6fusD4aOclqPk97VrL4/hT50qhX9tlWeJ2UvyWXlIH+svw/6gAG0rzJxbdpxU3zlt3jylmMb7RwXYZgKY/sW2iW6jZFsA=
  app: epichatfront