language: node_js
node_js:
- 8
deploy:
  provider: heroku
  api_key:
    secure: c877+vnR7foL9kzzHsO2oczJH7YhOoV+nbME17AT3fJWDUOJxikV0cxCV1dVF3QhsKHswrPjKiiMseo7BHFHkE0D5Rcyppvok9arM7ypoYI/NG8LMfE7r8lCziVMTMyR3j2SD1GIIPvBRedq71pB/y7uC4GzCA/pZDPPD00LuSG4y3IcQUMo5qsP8wqowseFsr6ODVotzVHZQFlVObvrHkkNkQw6FD6U5GR0O2ZM/6XG5hoJXNLcHC+ndtmLGWRtFOrxybaVybdH93MmDo1yRsJadq5nDpJrolLnKGCQccMQANLiCSxyT1lNz3o5K2Bu1MaurBIUnhYFbGVJAunHvYRPM97eRGlTTp/gpQ2gEiWF5EJGHVf2o87HKpOexOC6B/WUhkzAXIwOQhO6XVkU8+BOW4+LbmJbAVmhje6xGy7TWkDATJDIU2XFj6kKHmkUB3O0wra/T9blCgnxmmzUaaCUB0kzOKhBA7FhpqujoLBH5oz4JuDWDGEy6kWGeYiRFMPZWex/82a5jzSHMNXQwtZuJWcRe8wkgQwtUsQ0g2BkkF1xwUvxicp7bpgkTtTAiv806uRE8VTnd6SJxQ0yoxVj74IhUTuClzK+YtVR4yruzQ9oAQrQWTBHKtSxzVWYStVu4TBlFch1SkZB2zLP3pElawBwt9VBeKMZL44oL2Y=
  app: epichatfront
