language: node_js
node_js:
- 8
deploy:
  provider: heroku
  api_key:
    secure: VmonoL6pUn0rxZSjWrZJ2OtdoposPEQMNBWWT4kdWx0DmEKAbtLy01N1tkmj73UHcxqPmLoGb6fcl+st7wfV9pBdo1F9dblimCDN5Y+Hx+5kEGomAwlGwBXmcf90wQMBPDBahBEbg7r4BKbkV02RALiomTRQbcFb5UVmLdvjonfYJdjiAGSeAnLsG9ksRKd+t6EMtBBjXicWWzxCawLax6e1/TlzV5YQhLemx8CrtJnEEXahzX2EVpJftc97bfQQEeW+Bnw5QjqPZOmK3ESkWcYAQUOr5Vt3yiS1uek5yvnqRxDCDOvsqjjIs0eMXTMWPo6tEvVfSZbL/A9d82CSuUXdRbK6JnY96GbCVSW7Z7EKFxk4OrF7a3jS+MTZ8SZF/88mCz/6tMki1jG2BcL1206jguokrjXgbbzrN8Xp4CSh2WPaLFxOQ4vzYzUasw4PWRDgajOEgEYjzDk4/POKcNTDvQCjpeQdIzX+VtBWDCLSk5tAjBYKiGc1EdP9szS/EP9g7zOMlikGE6CCF9ciSStn4E8uEOGq0jR3AX2SAQ0nqEUIWdPVpDr6G7+WK1efi3cYOlvufskZeIkYyFpr/qpXrxDn2umPkVUeTRhrIIJzNLaxb2FdQOG0xrRLvNyYOOCv6tUjuKv3yS/2j5W0ApaOKvH4wSzoO+BHcjYBcg8=
  app: epichatfront
